name: 'Setup Build Dependencies'
description: 'Install system dependencies and capnproto for building mina-network-debugger'
runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          curl \
          clang \
          make \
          pkg-config \
          libelf-dev \
          protobuf-compiler \
          libbz2-dev \
          libssl-dev \
          libbpf-dev

    - name: Build and install capnproto 0.10.2
      shell: bash
      run: |
        if command -v capnp &> /dev/null; then
          echo "Cap'n Proto already installed: $(capnp --version)"
        else
          curl -sSL https://capnproto.org/capnproto-c++-0.10.2.tar.gz | tar -zxf -
          cd capnproto-c++-0.10.2
          ./configure
          make -j$(nproc)
          sudo make install
          cd ..
          rm -rf capnproto-c++-0.10.2
        fi
